-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-09-16 20:23:03 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on
SPOOL brm_schema_output.txt


DROP TABLE COMBINATION_RATE CASCADE CONSTRAINTS 
;

DROP TABLE COMBINATIONS CASCADE CONSTRAINTS 
;

DROP TABLE CUSTOMER CASCADE CONSTRAINTS 
;

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS 
;

DROP TABLE JOB CASCADE CONSTRAINTS 
;

DROP TABLE JOBCERT CASCADE CONSTRAINTS 
;

DROP TABLE PURPOSE CASCADE CONSTRAINTS 
;

DROP TABLE QUOTE CASCADE CONSTRAINTS 
;

DROP TABLE ROLE CASCADE CONSTRAINTS 
;

DROP TABLE TRAILER CASCADE CONSTRAINTS 
;

DROP TABLE TRAILERTYPE CASCADE CONSTRAINTS 
;

DROP TABLE TRUCK CASCADE CONSTRAINTS 
;

DROP TABLE TRUCKTYPE CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE COMBINATION_RATE 
    ( 
     comb_hire_rate         NUMBER (9,2)  NOT NULL , 
     PURPOSE_purp_no        NUMBER (6)  NOT NULL , 
     COMBINATIONS_comb_code VARCHAR2 (12)  NOT NULL 
    ) 
;

ALTER TABLE COMBINATION_RATE 
    ADD CONSTRAINT COMBINATION_RATE_PK PRIMARY KEY ( PURPOSE_purp_no, COMBINATIONS_comb_code ) ;

CREATE TABLE COMBINATIONS 
    ( 
     comb_code            VARCHAR2 (12)  NOT NULL , 
     TRAILER_trailer_code VARCHAR2 (5)  NOT NULL , 
     TRUCK_VIN            VARCHAR2 (17)  NOT NULL 
    ) 
;

ALTER TABLE COMBINATIONS 
    ADD CONSTRAINT COMBINATIONS_PK PRIMARY KEY ( comb_code ) ;

CREATE TABLE CUSTOMER 
    ( 
     cust_no       NUMBER (6)  NOT NULL , 
     given_name    VARCHAR2 (40)  NOT NULL , 
     family_name   VARCHAR2 (40)  NOT NULL , 
     buisness_name VARCHAR2 (40) , 
     address       VARCHAR2 (200)  NOT NULL , 
     contact_no    NUMBER (20)  NOT NULL 
    ) 
;

ALTER TABLE CUSTOMER 
    ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( cust_no ) ;

CREATE TABLE EMPLOYEE 
    ( 
     given_name      CHAR (40)  NOT NULL , 
     family_name     CHAR (40)  NOT NULL , 
     contact_no      NUMBER (15)  NOT NULL , 
     salary          NUMBER (7,2)  NOT NULL , 
     TFN             NUMBER (9)  NOT NULL , 
     licence_no      VARCHAR2 (20) , 
     ROLE_role_name  VARCHAR2 (16)  NOT NULL , 
     manager_emp_no  NUMBER (6) , 
     emp_no          NUMBER (6)  NOT NULL , 
     EMPLOYEE_emp_no NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY ( emp_no ) ;

CREATE TABLE JOB 
    ( 
     job_no                 VARCHAR2 (10)  NOT NULL , 
     pickup_dt              DATE  NOT NULL , 
     int_drop_dt            DATE  NOT NULL , 
     paid_flag              CHAR (2)  NOT NULL , 
     job_cost               NUMBER (10)  NOT NULL , 
     COMBINATIONS_comb_code VARCHAR2 (12)  NOT NULL , 
     QUOTE_quote_no         NUMBER (6)  NOT NULL , 
     EMPLOYEE_emp_no        NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT check_paid_flag 
    CHECK (paid_flag IN ('N', 'Y')) 
;

COMMENT ON COLUMN JOB.paid_flag IS 'Y- Customer Paid, N- Customer No Paid' 
;
CREATE UNIQUE INDEX JOB__IDX ON JOB 
    ( 
     QUOTE_quote_no ASC 
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT JOB_PK PRIMARY KEY ( job_no ) ;

CREATE TABLE JOBCERT 
    ( 
     jobcert_id      NUMBER (6)  NOT NULL , 
     JOB_job_no      VARCHAR2 (10)  NOT NULL , 
     EMPLOYEE_emp_no NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE JOBCERT 
    ADD CONSTRAINT JOBCERT_PK PRIMARY KEY ( jobcert_id ) ;

ALTER TABLE JOBCERT 
    ADD CONSTRAINT Key_2 UNIQUE ( JOB_job_no ) ;

CREATE TABLE PURPOSE 
    ( 
     purp_no   NUMBER (6)  NOT NULL , 
     purp_desc VARCHAR2 (60)  NOT NULL 
    ) 
;

ALTER TABLE PURPOSE 
    ADD CONSTRAINT PURPOSE_PK PRIMARY KEY ( purp_no ) ;

CREATE TABLE QUOTE 
    ( 
     quote_no         NUMBER (6)  NOT NULL , 
     prepared_dt      DATE  NOT NULL , 
     prefer_start_dt  DATE  NOT NULL , 
     pickup_location  VARCHAR2 (200)  NOT NULL , 
     dropof_location  VARCHAR2 (200)  NOT NULL , 
     quote_cost       NUMBER (10,2)  NOT NULL , 
     CUSTOMER_cust_no NUMBER (6)  NOT NULL , 
     PURPOSE_purp_no  NUMBER (6)  NOT NULL , 
     EMPLOYEE_emp_no  NUMBER (6)  NOT NULL 
    ) 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT QUOTE_PK PRIMARY KEY ( quote_no ) ;

CREATE TABLE ROLE 
    ( 
     role_name VARCHAR2 (16)  NOT NULL 
    ) 
;

ALTER TABLE ROLE 
    ADD CONSTRAINT ROLE_PK PRIMARY KEY ( role_name ) ;

CREATE TABLE TRAILER 
    ( 
     trailer_code              VARCHAR2 (5)  NOT NULL , 
     purch_date                DATE  NOT NULL , 
     purch_price               NUMBER (10,2)  NOT NULL , 
     trailerdecom_date         DATE , 
     TRAILERTYPE_trailer_model VARCHAR2 (40)  NOT NULL , 
     TRAILERTYPE_trailer_manu  VARCHAR2 (30)  NOT NULL 
    ) 
;

ALTER TABLE TRAILER 
    ADD CONSTRAINT TRAILER_PK PRIMARY KEY ( trailer_code ) ;

CREATE TABLE TRAILERTYPE 
    ( 
     trailer_manu  VARCHAR2 (30)  NOT NULL , 
     trailer_model VARCHAR2 (40)  NOT NULL 
    ) 
;

ALTER TABLE TRAILERTYPE 
    ADD CONSTRAINT TRAILERTYPE_PK PRIMARY KEY ( trailer_model, trailer_manu ) ;

CREATE TABLE TRUCK 
    ( 
     VIN                   VARCHAR2 (17)  NOT NULL , 
     rego_no               VARCHAR2 (40)  NOT NULL , 
     total_km              NUMBER (7)  NOT NULL , 
     lastserv_km           NUMBER (7)  NOT NULL , 
     purch_date            DATE  NOT NULL , 
     purch_price           NUMBER (10,2)  NOT NULL , 
     truckdecom_date       DATE , 
     TRUCKTYPE_truck_manu  VARCHAR2 (30)  NOT NULL , 
     TRUCKTYPE_truck_model VARCHAR2 (40)  NOT NULL 
    ) 
;

ALTER TABLE TRUCK 
    ADD CONSTRAINT TRUCK_PK PRIMARY KEY ( VIN ) ;

CREATE TABLE TRUCKTYPE 
    ( 
     truck_manu  VARCHAR2 (30)  NOT NULL , 
     truck_model VARCHAR2 (40)  NOT NULL 
    ) 
;

ALTER TABLE TRUCKTYPE 
    ADD CONSTRAINT TRUCKTYPE_PK PRIMARY KEY ( truck_manu, truck_model ) ;

ALTER TABLE TRAILER 
    ADD CONSTRAINT classifiesv1 FOREIGN KEY 
    ( 
     TRAILERTYPE_trailer_model,
     TRAILERTYPE_trailer_manu
    ) 
    REFERENCES TRAILERTYPE 
    ( 
     trailer_model,
     trailer_manu
    ) 
;

ALTER TABLE COMBINATION_RATE 
    ADD CONSTRAINT COMBINATION_RATE_PURPOSE FOREIGN KEY 
    ( 
     PURPOSE_purp_no
    ) 
    REFERENCES PURPOSE 
    ( 
     purp_no
    ) 
;

ALTER TABLE COMBINATION_RATE 
    ADD CONSTRAINT combinations_combination_rate FOREIGN KEY 
    ( 
     COMBINATIONS_comb_code
    ) 
    REFERENCES COMBINATIONS 
    ( 
     comb_code
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT COMBINATIONS_JOB FOREIGN KEY 
    ( 
     COMBINATIONS_comb_code
    ) 
    REFERENCES COMBINATIONS 
    ( 
     comb_code
    ) 
;

ALTER TABLE JOBCERT 
    ADD CONSTRAINT EMPLOYEE_JOB_CERT FOREIGN KEY 
    ( 
     EMPLOYEE_emp_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     emp_no
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_MANAGER FOREIGN KEY 
    ( 
     EMPLOYEE_emp_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     emp_no
    ) 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT EMPLOYEE_QUOTE FOREIGN KEY 
    ( 
     EMPLOYEE_emp_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     emp_no
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT JOB_EMPLOYEE FOREIGN KEY 
    ( 
     EMPLOYEE_emp_no
    ) 
    REFERENCES EMPLOYEE 
    ( 
     emp_no
    ) 
;

ALTER TABLE JOBCERT 
    ADD CONSTRAINT JOB_JOB_CERT FOREIGN KEY 
    ( 
     JOB_job_no
    ) 
    REFERENCES JOB 
    ( 
     job_no
    ) 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT purpose_quote FOREIGN KEY 
    ( 
     PURPOSE_purp_no
    ) 
    REFERENCES PURPOSE 
    ( 
     purp_no
    ) 
;

ALTER TABLE QUOTE 
    ADD CONSTRAINT QUOTE_CUSTOMER FOREIGN KEY 
    ( 
     CUSTOMER_cust_no
    ) 
    REFERENCES CUSTOMER 
    ( 
     cust_no
    ) 
;

ALTER TABLE JOB 
    ADD CONSTRAINT QUOTE_JOB FOREIGN KEY 
    ( 
     QUOTE_quote_no
    ) 
    REFERENCES QUOTE 
    ( 
     quote_no
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT ROLE_EMPLOYEE FOREIGN KEY 
    ( 
     ROLE_role_name
    ) 
    REFERENCES ROLE 
    ( 
     role_name
    ) 
;

ALTER TABLE COMBINATIONS 
    ADD CONSTRAINT TRAILER_COMBINATION FOREIGN KEY 
    ( 
     TRAILER_trailer_code
    ) 
    REFERENCES TRAILER 
    ( 
     trailer_code
    ) 
;

ALTER TABLE COMBINATIONS 
    ADD CONSTRAINT TRUCK_COMBINATION FOREIGN KEY 
    ( 
     TRUCK_VIN
    ) 
    REFERENCES TRUCK 
    ( 
     VIN
    ) 
;

ALTER TABLE TRUCK 
    ADD CONSTRAINT TRUCK_TYPE_TRUCK FOREIGN KEY 
    ( 
     TRUCKTYPE_truck_manu,
     TRUCKTYPE_truck_model
    ) 
    REFERENCES TRUCKTYPE 
    ( 
     truck_manu,
     truck_model
    ) 
;

SPOOL off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             1
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
